version: '2'
services:
        redis7001:
          image: redis:latest
          privileged: true
          networks:
            - pxc-net
          ports:
            - "7001:7001"
            - "17001:17001"
          command: redis-server /usr/local/etc/redis/redis.conf
          volumes:
            - ./data/7001:/data
            - ./data/7001/redis.conf:/usr/local/etc/redis/redis.conf
        redis7002:
          image: redis:latest
          privileged: true
          networks:
            - pxc-net
          ports:
            - "7002:7002"
            - "17002:17002"
          command: redis-server /usr/local/etc/redis/redis.conf
          volumes:
            - ./data/7002:/data
            - ./data/7002/redis.conf:/usr/local/etc/redis/redis.conf
        redis7003:
          image: redis:latest
          privileged: true
          networks:
            - pxc-net
          ports:
            - "7003:7003"
            - "17003:17003"
          command: redis-server /usr/local/etc/redis/redis.conf
          volumes:
            - ./data/7003:/data
            - ./data/7003/redis.conf:/usr/local/etc/redis/redis.conf
        redis7004:
          image: redis:latest
          privileged: true
          networks:
            - pxc-net
          ports:
            - "7004:7004"
            - "17004:17004"
          command: redis-server /usr/local/etc/redis/redis.conf
          volumes:
            - ./data/7004:/data
            - ./data/7004/redis.conf:/usr/local/etc/redis/redis.conf
        redis7005:
          image: redis:latest
          privileged: true
          networks:
            - pxc-net
          ports:
            - "7005:7005"
            - "17005:17005"
          command: redis-server /usr/local/etc/redis/redis.conf
          volumes:
            - ./data/7005:/data
            - ./data/7005/redis.conf:/usr/local/etc/redis/redis.conf
        redis7006:
          image: redis:latest
          privileged: true
          networks:
            - pxc-net
          ports:
            - "7006:7006"
            - "17006:17006"
          command: redis-server /usr/local/etc/redis/redis.conf
          volumes:
            - ./data/7006:/data
            - ./data/7006/redis.conf:/usr/local/etc/redis/redis.conf
networks:
        pxc-net:
            driver: bridge
